### PR TITLE
#243 + compilation fixes

### PR DESCRIPTION
**Pull request by rupakbajgain**
GL painter does not support hatch.
Below are files i am testing with, i don't know why one fails.
[build.zip](https://github.com/LibreCAD/LibreCAD_3/files/3882366/build.zip)
2 fails.
& no color from layer.

### CODE REVIEW

**Comment by rupakbajgain** [comment]
The openGL painter is fast,
The program always closes with segmentation fault.

**Comment by feragon** [comment]
This is what happens when I open 2:
image

I don't have any segault. Try to run LibreCAD with gdb to check where it happens.

**Comment by feragon** [comment]
Can you test your layer color problem again with #245?

**Comment by rupakbajgain** [comment]
sorry for being unclear. all of them are from diffrent conditions.

if you use cairo painter then 1 will have hatch. but not 2. i dont know why this happens as log shows all datas are loaded. the hatch will be also drawn but without the loop.  i mean the for loop of lcvhatch. the only diffenence in these imges is that i have used diffrent layer for hatch for 1. 

in file 1. if i check the layers. all of them have white foreground so i have white color only for hatch.

if i use opengl painter and run program . only after i close my program. i get segfault and my program will terminte. i mean i see segfault in terminal after program is closed.

**Comment by rupakbajgain** [comment]
@feragon. 2 will not show hatch any way. it was old problem . i thought it was due to ownership of variables so shared ptr was freed. but later i found same problem. i wrote code using 1. again i created 2 and it failed. and i reembred the old problem. this is same

**Comment by rupakbajgain** [comment]
@feragon. 2 will not show hatch any way. it was old problem . i thought it was due to ownership of variables so shared ptr was freed. but later i found same problem. i wrote code using 1. again i created 2 and it failed. and i remembered the old problem. this is same.

And i cannot get hatch using open gl painter in 1. i looked the code and i think it should have worked.

**Comment by rupakbajgain** [comment]
ok i will try 245.

**Comment by sckorpio** [comment]
Hello,
As far my understanding hatch is like "a filled circle",
Actually GL painter can surely render a filled circle..
it need calls like.. painter.circle()..painter.fill()...  
Screenshot from 2019-11-24 11-50-59

**Comment by rvt** [comment]
> Hello,
> As far my understanding hatch is like "a filled circle",
> Actually GL painter can surely render a filled circle..
> it need calls like.. painter.circle()..painter.fill()...

Unfortunately hatches are more complex due to the different fill styles.... Like brick style, crossed lines etc I wound a crappy pin, but I think when seeing this you will get the idea.

https://www.pinterest.com/pin/239183430182012266/

**Comment by rupakbajgain** [comment]
Actually hatch of circle is arc.

**Comment by rupakbajgain** [comment]
For cairo my output is 
Screenshot_20191125_073107
This is my output of 1 using cairo, i think the color problem is fixed now, but i cannot get back to cairo after i merged. The hatch for painter is of Loop of (Arc, Line, Polyline, ellipse, spline) , and pattern to hatch with in them, according to dxf.

**Comment by rupakbajgain** [comment]
No empty circle of top, i updated image.

**Comment by rvt** [comment]
sounds like the unit and integration tests need to get updated...

**Comment by rupakbajgain** [comment]
hello @sckorpio . i tried using
```
painter.circle(0, 0, 20);
painter.fill();
```
i cannot get a hatch. is it rendering back side. stroke method is ok and i get circle. i checked opengl painter code. i think the fill and stroke method  should end current entity and start new shape entity. is it happening so? 

i think there are my old hatch code in master too. try opeaning any file with hatch. the code i am changing is in lcviewernoqt/drawitems/lcvhatch.cpp

**Pull request closed without merging**
