### PR TITLE
About

### PR DESCRIPTION
**Pull request by rupakbajgain**
Polyline with width

### CODE REVIEW

**Comment by rupakbajgain** [comment]
<details>
<summary>LibreCAD 3</summary>
<table><tr><td>Version</td><td>: 3.0</td></tr>
<tr><td>Compiler</td><td>: GNU GCC 9.3.0</td></tr>
<tr><td>Compiled on</td><td>: 2020-07-24 00:21:19</td></tr>
<tr><td>Build info</td><td>: branch about - commit 1c80874f</td></tr>
</table>
</details>
<details>
<summary>External Dependencies</summary>
<table><tr><td>Qt Version</td><td>: 5.12.5</td></tr>
<tr><td>Boost Version</td><td>: 1.67.0</td></tr>
<tr><td>Lua Version</td><td>: Lua 5.2</td></tr>
<tr><td>libdxfrw Version</td><td>: 0.6.3</td></tr>
<tr><td>OpenGL Version</td><td>: 3.0</td></tr>
<tr><td>CMake Version</td><td>: 3.16.3</td></tr>
</table>
</details>
<details>
<summary>OS</summary>
<table><tr><td>system name</td><td>: Linux</td></tr>
<tr><td>release</td><td>: 5.5.0-kali2-amd64</td></tr>
<tr><td>version</td><td>: #1 SMP Debian 5.5.17-1kali1 (2020-04-21)</td></tr>
<tr><td>machine</td><td>: x86_64</td></tr>
<tr><td>System</td><td>: Kali GNU/Linux Rolling</td></tr>
<tr><td>Build Architecture</td><td>: x86_64</td></tr>
<tr><td>Current Architecture</td><td>: x86_64</td></tr>
<tr><td>Kernel Type</td><td>: linux</td></tr>
<tr><td>Kernel Version</td><td>: 5.5.0-kali2-amd64</td></tr>
<tr><td>Product Type</td><td>: kali</td></tr>
<tr><td>Product Version</td><td>: 2020.2</td></tr>
</table>
</details>

**Comment by rupakbajgain** [comment]
#268

**Comment by rupakbajgain** [comment]
<details>
<summary>LibreCAD 3</summary>
<table><tr><td>Version</td><td>: 3.0</td></tr>
<tr><td>Compiler</td><td>: GNU GCC 9.3.0</td></tr>
<tr><td>Compiled on</td><td>: 2020-07-24 00:42:09</td></tr>
<tr><td>Build info</td><td>: branch about - commit 16a949c3</td></tr>
</table>
</details>
<details>
<summary>External Dependencies</summary>
<table><tr><td>Qt Version</td><td>: 5.12.5</td></tr>
<tr><td>Boost Version</td><td>: 1.67.0</td></tr>
<tr><td>Lua Version</td><td>: Lua 5.2</td></tr>
<tr><td>libdxfrw Version</td><td>: 0.6.3</td></tr>
<tr><td>OpenGL Version</td><td>: 3.0</td></tr>
<tr><td>CMake Version</td><td>: 3.16.3</td></tr>
</table>
</details>
<details>
<summary>OS</summary>
<table><tr><td>system name</td><td>: Linux</td></tr>
<tr><td>release</td><td>: 5.5.0-kali2-amd64</td></tr>
<tr><td>version</td><td>: #1 SMP Debian 5.5.17-1kali1 (2020-04-21)</td></tr>
<tr><td>machine</td><td>: x86_64</td></tr>
<tr><td>System</td><td>: Kali GNU/Linux Rolling</td></tr>
<tr><td>Build Architecture</td><td>: x86_64</td></tr>
<tr><td>Current Architecture</td><td>: x86_64</td></tr>
<tr><td>Kernel Type</td><td>: linux</td></tr>
<tr><td>Kernel Version</td><td>: 5.5.0-kali2-amd64</td></tr>
<tr><td>Product Type</td><td>: kali</td></tr>
<tr><td>Product Version</td><td>: 2020.2</td></tr>
</table>
</details>

**Comment by feragon** [comment]
Thanks 👍

**Comment by rupakbajgain** [comment]
#268 should be closed 
<details>
<summary>LibreCAD 3</summary>
<table><tr><td>Version</td><td>: 3.0</td></tr>
<tr><td>Compiler</td><td>: GNU GCC 9.3.0</td></tr>
<tr><td>Compiled on</td><td>: 2020-07-29 10:04:00</td></tr>
<tr><td>Build info</td><td>: branch rupak - commit 31a032a1</td></tr>
</table>
</details>
<details>
<summary>External Dependencies</summary>
<table><tr><td>Qt Version</td><td>: 5.12.8</td></tr>
<tr><td>Boost Version</td><td>: 1.71.0</td></tr>
<tr><td>Lua Version</td><td>: Lua 5.2</td></tr>
<tr><td>libdxfrw Version</td><td>: 0.6.3</td></tr>
<tr><td>OpenGL Version</td><td>: 3.0</td></tr>
<tr><td>CMake Version</td><td>: 3.16.3</td></tr>
</table>
</details>
<details>
<summary>OS</summary>
<table><tr><td>system name</td><td>: Linux</td></tr>
<tr><td>release</td><td>: 5.4.0-42-generic</td></tr>
<tr><td>version</td><td>: #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020</td></tr>
<tr><td>machine</td><td>: x86_64</td></tr>
<tr><td>System</td><td>: Ubuntu 20.04.1 LTS</td></tr>
<tr><td>Build Architecture</td><td>: x86_64</td></tr>
<tr><td>Current Architecture</td><td>: x86_64</td></tr>
<tr><td>Kernel Type</td><td>: linux</td></tr>
<tr><td>Kernel Version</td><td>: 5.4.0-42-generic</td></tr>
<tr><td>Product Type</td><td>: ubuntu</td></tr>
<tr><td>Product Version</td><td>: 20.04</td></tr>
</table>
</details>

**Pull request merged**
