### PR TITLE
Split polyline + Trim + Select by clicking path(onEntity)

### PR DESCRIPTION
**Pull request by rupakbajgain**

### CODE REVIEW

**Comment by rupakbajgain** [comment]
looks selectionChanged does not work,

the trim work as.
1. select 1 entity 
2. click trim
3. select point to trim

or, 
1. select multiple entities
2. click trim

**Comment by rupakbajgain** [comment]
#329

**Comment by rupakbajgain** [comment]
Select entity by clicking on it not from box.

**Comment by rupakbajgain** [comment]
Looks like lc::math::getCorrectAngle in C++ and table.remove in lua are quite dangerous functions.

**Comment by feragon** [comment]
Thanks :+1:

**Pull request merged**
