### PR TITLE
New view 

### PR DESCRIPTION
**Pull request by rupakbajgain**

### CODE REVIEW

**Comment by rupakbajgain** [comment]
- The second model view is not working properly, i think it is because the point it receives for event is not proper.

**Comment by feragon** [comment]
I tested it, this looks promising.
I think Lua is not receiving the events of the right model, but it's not a problem as only the first model needs to be edited.

**Comment by rupakbajgain** [comment]
https://knowledge.autodesk.com/support/autocad/learn-explore/caas/simplecontent/content/making-split-view-model-space.html

Both of them should be editable.  I prefer splitter like in blender.

**Comment by feragon** [comment]
https://github.com/LibreCAD/LibreCAD_3/blob/10f568463aa5200c947ac4e0261096d9f5ba9980/lcUILua/ui/cadmdichild.lua#L19

You can find here the connections of Qt signals here. It uses CadMdiChild::viewer() so the events of the second viewer are ignored.
I think here you can use CadMdiChild as a proxy for events of the LCADViewers, or use the QWidget::mousePressEvent and find the origin child after.

**Pull request closed without merging**
